linux-sunxi/meta-sunxi

recipes-kernel/linux/linux.inc
recipes-kernel/linux/linux_3.4.bb

Removing the linux.inc introduced an unnecessary dependency on meta-oe.
Add the latest linux.inc from meta-oe to the layer and change path.

linux: add linux.inc again

---

conf/machine/olinuxino-a20.conf

Fixes a typo in KERNEL_DEVICETREE.

olinuxino-a20: fix KERNEL_DEVICETREE

---

recipes-kernel/linux/linux_4.1.3.bb
recipes-kernel/linux/linux_git.bb

Per default use stable kernel by downloading tar.xz (fast download).
Optional use latest mainline kernel by git fetch. Must be enabled
in linux_git.bb by setting DEFAULT_PREFERENCE to "1".

kernel: use tar.xz, git optional

---

conf/machine/meleg.conf
recipes-bsp/u-boot/u-boot-sunxi.bb

Mainline u-boot uses a different name for the configuration for the Mele G.
Use correct name for mainline, use old name for sunxi u-boot.

Use correct u-boot name for meleg

---

README.md

If the user wants to build the sunxi version of the kernel they can specify
the PREFERRED_PROVIDER block in their conf/local.conf (i.e. they don't need to
edit the layer explicitly).
Also, now that gcc-5.2 is the default on master, inform the user how they can
continue to build the sunxi version (3.4%) version of the kernel by forcing
the compiler to version 4.9.

README.md: improve instructions for sunxi versions

---

recipes-graphics/libgles/sunxi-mali_git.bb

When trying to build sunxi-mali with current master there is a strip
error introduced in a patch trying to strip the rootfs. Disable striping.
Also fix an error where external recipes would not find the libaries.

sunxi-mali: fix build errors with current master

---

recipes-kernel/linux/linux-sunxi/0001-compiler-gcc5.patch
recipes-kernel/linux/linux-sunxi/0002-use-static-inline-in-ARM-ftrace.patch
recipes-kernel/linux/linux-sunxi_3.4.bb

The linux-sunxi 3.4 kernel could not be compiled with gcc5 (which
is standard in master now). Add two patches to make it compile again.
- Add missing compiler-gcc5.h
- Fix "multiple definition of `return_address'" errors
Open issue: All realtek wifi drivers fail to compile. Because of this
keep info to switch back to gcc4 in readme.

linux-sunxi: add patches for gcc5

---

recipes-kernel/linux/linux-sunxi_3.4.bb

ERROR: ParseError at meta-sunxi/recipes-kernel/linux/linux-sunxi_3.4.bb:17:
unparsed line: SRC_URI

linux-sunxi_3.4.bb: add line continuation

---

recipes-kernel/linux/linux-sunxi_3.4.bb

When building a second time, allow the 'rm' command to fail silently since
these files may have been removed from a failed previous build.

linux-sunxi_3.4.bb: allow rm to fail

---

recipes-graphics/libgles/sunxi-mali_git.bb

The mali driver supports OpenGL ES and doesn't require OpenGL in any way. It
is completely feasible to install mali and run OpenGL ES-only apps against it
without any need for OpenGL whatsoever.

sunxi-mali: remove opengl requirement

---

classes/sdcard_image-sunxi.bbclass
recipes-kernel/linux/linux-sunxi_3.4.bb

Remove image dependency on building fex files which are not needed
any more for mainline kernel (replaced by devicetree).
Add dependency for fex to linux-sunxi kernel.
Also update to latest sunxi-linux revision.

Remove image dependency on fex for mainline

---

recipes-graphics/libgles/sunxi-mali_git.bb

Here are two patches against the sunxi-mali_git.bb recipe.
The first one (remove EXTRA_OECONF) is required to build successfully. I'm not entirely sure what changed, but something changed (I assume) elsewhere and this recipe stopped working.
The second one is a bit more cosmetic and removes the deprecated warning from a build.

2 sunxi-mali_git patches

---

conf/machine/olinuxino-a13som.conf

Missing kernel device tree definition added.
U-Boot definiton fixed to used corrected defconfig file.

Fix for Olimex A13 SOM

---

recipes-graphics/libgles/sunxi-mali_git.bb

This will now error out during parsing instead of during do_compile as
well as having a better error message.
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>

sunxi-mali: error out earlier on non-hf builds

---

classes/sdcard_image-sunxi.bbclass

The IMAGE_NAME variable already contains the date and time so it is
redundant to also include the date again with IMAGEDATESTAMP
when writing to image-version-info in the boot partition.

sdcard_image-sunxi.bbclass: remove redundant IMAGEDATESTAMP

---

recipes-bsp/u-boot/u-boot_2016.09.01.bb

Commit b36056af20e981433f143556d511dec5644930fc in oe-core master
(matching commit in poky master is a40f5d34065129ab19a3c981cbb38f854e9ae0ec)
moved some bits out of u-boot.inc (from oe-core) into u-boot-common_${PV}.inc. This
breaks many u-boot recipes in the wild, including u-boot_2016.09.01 from this layer
since the variable S itself results undefined.
Explicitly setting S fixes the issue.

u-boot_2016.09.01: fix build with new upstream u-boot.inc

---

README.md

The linux-sunxi can now be built with GCC 6 so the GCCVERSION variable
doesn't need to be set anymore.

README.md: Clean up build instructions

---

conf/machine/olinuxino-a20som.conf

* Added missing kernel device tree definition.
* Updated U-Boot definiton.

Fix Olimex A20 SOM configuration

---

recipes-graphics/libgles/sunxi-mali_git.bb

The bb.data API is deprecated, use d.getVar instead.

sunxi-mali: Use d.getVar

---

conf/machine/include/sun8i.inc
conf/machine/orange-pi-one.conf
conf/machine/pcduino.conf
recipes-bsp/u-boot/u-boot_2016.11.bb
recipes-graphics/libgles/sunxi-mali_git.bb
recipes-kernel/linux/linux_git.bb

This patch set implements the following pieces:
- add support for Orange Pi One board
- bump PV for Linux git revision
- minor fixes for sunxi-mali-test package

Add support for Orange Pi One board

---

recipes-kernel/linux/linux_4.4.40.bb

Previous version (4.4.6) was very old, therefore it was updated to 4.4.40 which is the latest 4.4.x version.

Bump Linux kernel version to 4.4.40

---

recipes-bsp/u-boot/u-boot-sunxi.bb
recipes-bsp/u-boot/u-boot-sunxi/0003-gcc6-fixes.patch

Fix the following build error when compiling u-boot-sunxi with gcc6:
linux/compiler-gcc6.h: No such file or directory

u-boot-sunxi: gcc6 fix

---

recipes-bsp/u-boot/files/U-Boot-PATCHv4-1-2-ARM-dts-sunxi-Change-node-name-for-pwrseq-pin-on-Olinuxino-lime2-emmc.patch
recipes-bsp/u-boot/files/U-Boot-PATCHv4-2-2-sun7i-Add-support-for-Olimex-A20-OLinuXino-LIME2-eMMC.patch
recipes-bsp/u-boot/u-boot_2017.03.bb

Update support for OLinuXino Lime2 eMMC by using patches proposed for upstream.
Patches picked from:
https://patchwork.ozlabs.org/patch/761510/
https://patchwork.ozlabs.org/patch/761512/

u-boot: update support for OLinuXino Lime2 eMMC

---

classes/sdcard_image-sunxi.bbclass

The older "IMAGE_DEPENDS_*" notation has been deprecated in favour of the
"do_image_...[depends]" notation.

sdcard_image-sunxi.bbclass: fix deprecated notation

---

recipes-kernel/linux/linux_4.4.40.bb
recipes-kernel/linux/linux_4.9.20.bb
recipes-kernel/linux/linux_git.bb

Adapt to upstream change in oe-core commit 03a00be: now Device Tree support is
automatically enabled when KERNEL_DEVICETREE is set.

linux: remove linux-dtb.inc

---

recipes-devtools/python/pya20_0.2.1.bb
recipes-devtools/python/pya20som_0.2.1.bb

The pypi now requires a https connection to download the files.
This PR changes the urls to https.

pypi requires a https connection

---

classes/sdcard_image-sunxi.bbclass

The comment says ext3 but the code says ext4, so fix the comment.

sdimage: fix incorrect comment

---

conf/machine/nanopi-neo-air.conf

We have devicetree and u-boot configs for the nanopi-neo-air, so add
them. As a basic test, this boots correctly on my nanopi-neo-air.

nanopi-neo-air: add new board

---

recipes-kernel/linux/linux-mainline_4.14.2.bb
recipes-kernel/linux/linux-mainline_git.bb
recipes-kernel/linux/linux.inc

Currently, using kernel config fragments is not working. If you try
adding one as documented in the Yocto Mega Manual [1], it will be
ignored.
There are two reasons for this:
- The config fragment logic is in kernel-yocto.bbclass, so we need to inherit
that (this is similar to what linux-raspberrypi does in meta-raspberrypi).
- We remove ${B}/.config, which undoes any config created by
kernel-yocto.
Fix this by inheriting kernel-yocto and not removing ${B}/.config. With
this patch, fragments are working. Note that we also need to add a few
variables (like KERNEL_KBUILD) to make kernel-yocto happy.
[1]
http://www.yoctoproject.org/docs/2.5/mega-manual/mega-manual.html#creating-the-append-file

linux: fix kernel config fragment support

---

recipes-kernel/linux/linux-mainline_4.14.2.bb
recipes-kernel/linux/linux-mainline_git.bb

The kernel-devicetree class now sets RDEPENDS_${KERNEL_PACKAGE_NAME}-base so we
needs to do the same, otherwise bitbake emits a warning. Reference change is
6c8c899 commit in oe-core.

linux-mainline: update RDEPENDS to match kernel naming

---

recipes-kernel/linux/linux-mainline_4.14.15.bb

This fixes an important brcmfmac use-after-free error:
brcmfmac: change driver unbind order of the sdio function devices
commit 5c3de777bdaf48bd0cfb43097c0d0fb85056cab7 upstream.
commit 01b43f2e3cad60c626daa9b174667a202cee6987 in linux-4.14.y
Without this change, I notice this error regularly when loading the wifi
firmware on the nanopi neo air.

linux-mainline: update to 4.14.15

---

recipes-kernel/linux/linux-mainline/0003-ARM-dts-nanopi-neo-air-Add-WiFi-eMMC.patch
recipes-kernel/linux/linux-mainline_4.14.15.bb

Backport a devicetree patch to enable wifi on the nanopi neo air.
The patch comes from here:
https://www.spinics.net/lists/arm-kernel/msg630904.html

nanopi-neo-air: add wifi DT patch

---

conf/machine/nanopi-neo-air.conf
conf/machine/nanopi-neo-plus2.conf
conf/machine/nanopi-neo.conf
conf/machine/nanopi-neo2.conf
conf/machine/orange-pi-one.conf
conf/machine/orange-pi-pc.conf
conf/machine/orange-pi-zero-plus2.conf
conf/machine/orange-pi-zero.conf
conf/machine/pcduino.conf
recipes-bsp/u-boot/files/u-boot-pylibfdt-native-build.patch
recipes-bsp/u-boot/u-boot_2018.03.bb
recipes-kernel/linux/linux-mainline/aarch64/defconfig

This patch series enables the nanopi neo plus 2 and the neo 2. With it, I'm able to boot successfully on both boards. It requires upgrading u-boot to v2018.03 in order to new u-boot configs.

Add the nanopi neo 2 and plus2

---

recipes-kernel/linux/linux-mainline/0003-ARM-dts-nanopi-neo-air-Add-WiFi-eMMC.patch

Signed-off-by: Florin Sarbu <florin@resin.io>

linux-mainline: Add back eMMC support for Nanopi Neo Air

---

recipes-bsp/u-boot/files/0001-nanopi_neo_air_defconfig-Enable-eMMC-support.patch
recipes-bsp/u-boot/u-boot_2018.03.bb

Signed-off-by: Florin Sarbu <florin@resin.io>

u-boot_2018.03.bb: Enable eMMC support for Nanopi Neo Air

---

conf/machine/include/sunxi.inc

This has been assigned a value containing a typo since 2015, my
assumption is that this is not used and hence we can simply drop
it. The typo is that the address contains a 'O' character instead
of '0', the last one is a zero.
Either way the kernel.bbclass will set a default value, that is:
UBOOT_LOADADDRESS ?= "${UBOOT_ENTRYPOINT}"
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

remove UBOOT_LOADADDRES 

---

conf/machine/orange-pi-pc-plus.conf

v2017.03 no longer exists and produces warnings if set as preferred:
NOTE: Resolving any missing task queue dependencies
NOTE: preferred version v2017.03% of u-boot not available (for item virtual/bootloader)
NOTE: versions of u-boot available: 1:2018.01 2:v2018.03+gitAUTOINC+f95ab1fb6e
NOTE: preferred version v2017.03% of u-boot not available (for item u-boot-dev)
NOTE: versions of u-boot available: 1:2018.01 2:v2018.03+gitAUTOINC+f95ab1fb6e
NOTE: preferred version v2017.03% of u-boot not available (for item u-boot)
NOTE: versions of u-boot available: 1:2018.01 2:v2018.03+gitAUTOINC+f95ab1fb6e
Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

orange-pi-pc-plus: update preferred U-boot version to v2018.03

---

recipes-kernel/linux/linux.inc

This change is an adaptation of commit 81e8a52e8e40e47 from poky/master.
Linux kernel build dependencies include bison since v4.16.
There were two different commits in poky adding those dependencies:
- poky/master: 81e8a52e8e40e47
- poky/sumo:   20e4d309e12bf10
However just adding bison-native to DEPENDS in linux or linux-yocto
class (as in poky/sumo) appears to be insufficient. The reason has
been clarified in 81e8a52e8e40e47 commit message:
"For linux-yocto, we also need to specify the compiler/tools dependencies
for the configme task since it executes before configure and hence the
main kernel build DEPENDS will not always be in the sysroot before it
executes. Without those dependencies the kernel will be incorrectly
configured (i.e. bison is missing) or the configuration will fail
the …

linux: specify explicit dependencies to configme task

---

classes/sdcard_image-sunxi.bbclass

DTB naming conventions has been changed on deploy, see:
poky: c5b70d7155a76b727400db225c446d1b2f7072a6
oe-core: 1860d9d3c62e2e94cd68a809385873ffd8270b6d
Modify sdcard_image-sunxi.bbclass accordingly.
Signed-off-by: Sergey Matyukevich <geomatsi@gmail.com>

sdcard_image-sunxi.bbclass: fix dtb naming conventions

---

conf/machine/pine64-plus.conf

Adds A64-based pine64-plus machine.
Signed-off-by: Matt Porter <mporter@konsulko.com>

Add pine64-plus machine

---

recipes-kernel/xradio-firmware/xradio-firmware.bb

I saw that the git repo used in the xradio-firmware recipe was outdated and updated it to the new location including the path changes, that came with it.

xradio-firmware: Update git repository und paths

---

conf/machine/include/sun50i.inc

In the latest OE, this file has been renamed. Since this board is
ARMv8-A, we should use the armv8a config instead of the armv8 config.

machine: use armv8a, not armv8

---

recipes-support/sunxi-tools/sunxi-tools_git.bb

sunxi-tools requires pkg-config native binary
which may be missing wihen pkgconfig class
is not inherited.
Signed-off-by: Dariusz Pelowski <dariusz.pelowski@gmail.com>

sunxi-tools: add inherit pkgconfig

---

recipes-graphics/libgles/sunxi-mali_git.bb
recipes-graphics/xorg-xserver/libdri2_git.bb

dri2proto and xextproto was replaced by xorgproto
see: https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#migration

misc: Replace dri2proto with xorgproto

---

conf/machine/include/sunxi.inc
recipes-kernel/linux/linux-mainline_4.19.46.bb
recipes-kernel/linux/linux-mainline_5.0.19.bb
recipes-kernel/linux/linux-mainline_5.2-rc2.bb

Added latest LTS (4.19 - default) + add latest stable 5.0.19 and bleeding edge 5.2-rc2
Rationale behind is to give meta-sunxi user possibility to verify latest stuff (I verified and all 3 boot frin on opi-pc-plus). Comments welcomed.

Sunxi kernel bump

---

conf/layer.conf

Update the layer compatibility information to indicate this layer is
compatible with "zeus".

LAYERSERIES_COMPAT: warrior -> zeus

---

conf/machine/nanopi-m1-plus.conf
conf/machine/nanopi-neo-air.conf
conf/machine/nanopi-neo-plus2.conf
conf/machine/nanopi-neo.conf
conf/machine/nanopi-neo2.conf
conf/machine/orange-pi-one.conf
conf/machine/orange-pi-pc-plus.conf
conf/machine/orange-pi-pc.conf
conf/machine/orange-pi-zero-plus2.conf
conf/machine/orange-pi-zero.conf
conf/machine/pcduino.conf
conf/machine/pine64-plus.conf

Remove pointless U-Boot PREFERRED_VERSION, as meta-sunxi no longer
provides its own u-boot recipe.

machine: remove U-Boot PREFERRED_VERSION

---

conf/machine/include/hardware/ap6212a.inc
conf/machine/nanopi-neo-plus2.conf
conf/machine/orange-pi-zero-plus2.conf
recipes-kernel/linux-firmware/linux-firmware_%.bbappend

Add support for AMPAK 6212A module with an include that:
1) installs kernel module
2) installs firmware
3) creates the required symlink with the AP6212 NVRAM file
Enable the support in the boards with the module, according to:
https://linux-sunxi.org/Table_of_Allwinner_based_boards
The link creation with compatible name works on kernels >= 5.0 and for
images including a package manager, otherwise a manual link still needs
to be created.

ap6212a.inc: add support for AMPAK 6212A

---

recipes-kernel/linux/linux-mainline/orange-pi-zero/0001-dts-orange-pi-zero-Add-wifi-support.patch

Wifi on Orange Pi Zero doesn't work with the current DTS because the compatible property is missing in the reg_vcc_wifi node after it's patched. This patch fixes the patch.

fixing missing 'compatible' property in reg_vcc_wifi node

---

conf/machine/include/sunxi.inc
recipes-kernel/linux/linux-mainline_4.19.103.bb
recipes-kernel/linux/linux-mainline_5.4.18.bb
recipes-kernel/linux/linux-mainline_5.5.3.bb

According to:
https://www.kernel.org/category/releases.html
version 5.4 is a longterm release, so:
- update longterm to 5.4.12
- update rc to 5.5-rc6
- remove stable, as longterm is the current most recent stable
- set 5.4 as the preferred version for linux-mainline

linux-mainline: update lt to 5.4.12, rc to 5.5-rc6

---

conf/machine/orange-pi-zero-plus2-h3.conf
recipes-kernel/linux-firmware/linux-firmware_%.bbappend

Add machine configuration for H3 variant of Orange Pi Zero Plus2.

conf: machine: add orange-pi-zero-plus2-h3

---

recipes-bsp/u-boot/files/0001-nanopi_neo_air_defconfig-Enable-eMMC-support.patch

This reverts commit ebde1a411c91a81246bf325a781634b8ac3e5ada.
Dunfell uses U-Boot 2020.01, so this patch shouldn't be applied in the
dunfell branch.

Revert "u-boot: rebase patch against v2020.04"

---

recipes-bsp/u-boot/files/0001-nanopi_neo_air_defconfig-Enable-eMMC-support.patch

The patch fails to apply with U-Boot 2020.01, which is present in the dunfell release.
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

u-boot: rebase nanopi_neo_air emmc patch

---

recipes-bsp/u-boot/files/0001-nanopi_neo_air_defconfig-Enable-eMMC-support.patch

This reverts commit 58d382d59892f48b1a36f225cf87b47be80cf76a.
This change was not needed on master. The patch was already correctly
refreshed on the dunfell branch to be compatible with the v2020.01
U-Boot release. It was done in the following commit: d0bbc7334d42

Revert "u-boot: rebase nanopi_neo_air emmc patch"

---

conf/machine/bananapi-m2plus.conf

Add machine configuration for H3 based Banana Pi M2+.
Signed-off-by: Marek Frydrysiak <marek.frydrysiak@gmail.com>

conf: machine: add bananapi-m2plus

---

conf/machine/include/sunxi.inc
wic/sunxi-sdcard-image.wks.in

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
Fixes: https://github.com/linux-sunxi/meta-sunxi/issues/255
Tested on the NanoPi M1
Another wks file for aarch64 would need to be added in order to fully replicate the functionality of the sunxi sdcard bbclass.

conf: sunxi.inc: add wks file for arm

---

recipes-bsp/u-boot/files/0002-Revert-sunxi-psci-avoid-error-address-of-packed-memb.patch
recipes-bsp/u-boot/u-boot_%.bbappend

Without this patch booting ends with Starting kernel ...

Fix orange-pi-zero booting with 2020.01 u-boot

---

classes/sdcard_image-sunxi.bbclass

Defaulting to the $MACHINE may lead to failure if the name was
longer than the limit of allowed volume label of fat (11 chars):
```
| Disk [...]zero-20210516083927.rootfs.sunxi-sdimg: 1011MB
| Sector size (logical/physical): 512B/512B
| Partition Table: msdos
| Disk Flags:
|
| Number  Start   End     Size    Type     File system  Flags
|  1      2097kB  44.0MB  41.9MB  primary               boot, lba
|  2      44.0MB  1009MB  965MB   primary
|
| mkfs.vfat: Label can be no longer than 11 characters
| mkfs.fat 4.2 (2021-01-31)
| WARNING: exit code 1 from a shell command.
```
I removed the label which is optional and defaults to no label. My personal feeling is that it is better to stick with the default. Otherwise the label will have to be cropped (and casted to uppercase).
Signed-off-by: …

remove boot partition label

---

conf/machine/include/hardware/ap6212a.inc
recipes-bsp/u-boot/u-boot_%.bbappend
recipes-devtools/python/pya20_0.2.12.bb
recipes-graphics/libgles/sunxi-mali_git.bb
recipes-graphics/libump/libump_git.bb
recipes-graphics/mesa/mesa_%.bbappend
recipes-graphics/tslib/tslib_1.1.bbappend.disabled
recipes-graphics/xorg-xserver/libdri2_git.bb
recipes-graphics/xorg-xserver/xf86-video-fbturbo_git.bb
recipes-graphics/xorg-xserver/xserver-xf86-config_0.1.bbappend
recipes-kernel/linux-firmware/linux-firmware_%.bbappend
recipes-kernel/linux/linux-mainline.inc
recipes-kernel/linux/linux-sunxi_3.4.bb
recipes-kernel/linux/linux.inc
recipes-kernel/xradio-firmware/xradio-firmware.bb
recipes-kernel/xradio/xradio.bb
recipes-multimedia/gstreamer/gst-plugin-cedar_git.bb
recipes-support/sunxi-tools/sunxi-tools_git.bb

OE/Yocto is migration towards new override syntax,
current master (upcomming honister release) will not
tolerate "_" as override operator.
New override syntax will be backported to
dunfell, gatesgarth, hardknott releases.
Signed-off-by: Bartłomiej Burdukiewicz <bartlomiej.burdukiewicz@gmail.com>

layer: convert to new override syntax :boom:

---

classes/sdcard_image-sunxi.bbclass
recipes-kernel/linux/linux.inc

sunxi-sdimg is not bootable because creation starts before ext filesystem is finished, this may be caused by new syntax, this fixes it

Fix SD Image Build for honister

---

recipes-bsp/sunxi-board-fex/sunxi-board-fex.bb
recipes-kernel/linux/linux-sunxi_3.4.bb

1. GitHub fetch protocol switch from "git" to "https"
2. Bump https://github.com/linux-sunxi/sunxi-boards version to the most recent "master" state

Minor updates

---

classes/sdcard_image-sunxi.bbclass

In function names, the "_" is the correct separator, and was not
replaced by ":".
Fixes mistake from commit 1f4dba30816a5f6da3dcfff8b9475bba938a01ca

classes/sdcard_image-sunxi.bbclass: fix misplaced ":"

---

conf/machine/orange-pi-r1.conf

Add the machine configuration for the Orange Pi R1.
Signed-off-by: Eric Bode <eric.bode@foundries.io>

conf: machine: add orange-pi-r1

---

recipes-graphics/libgles/sunxi-mali_git.bb

fix the following linter warnings
- WARNING: sunxi-mali-git-r0 do_unpack: URL: gitsm://github.com/linux-sunxi/sunxi-mali.git uses git protocol which is no longer supported by github. Please change to ;protocol=https in the url.
- WARNING: sunxi-mali-git-r0 do_unpack: URL: gitsm://github.com/linux-sunxi/sunxi-mali.git does not set any branch parameter. The future default branch used by tools and repositories is uncertain and we will therefore soon require this is set in all git urls.

libgles: sunxi-mali: fix linter warnings

---

conf/machine/include/sun5i.inc

Cortex-A8 architecture is ARMv7A. Using the wrong path was causing build failures

 Use correct arch in sun5i.inc - Kirkstone

---

conf/machine/bananapi-m2-zero.conf
recipes-kernel/linux/linux-mainline.inc
recipes-kernel/linux/linux-mainline/0003-dts-allwinner-bananapi-m2-zreo-Enforce-consistent-MM.patch

- Add a new machine for banana pi M2 zero
- Fix #354 : create alias to enforce mmc numbers

Banana pi zero and fix to boot stuck

---

conf/machine/orange-pi-one-plus.conf

Tested on the target with image 'core-image-base'

conf: machine: Add "Orange Pi One Plus" support

---

recipes-bsp/u-boot/files/0004-i2c-mvtwsi-Add-compatible-string-for-allwinner-sun4i.patch
recipes-bsp/u-boot/u-boot_%.bbappend

This commit backports an u-boot patch that adds a compatible string for the Allwinner Sun4i-A10 I2C controller.
This will fix the boot process freeze after SPL stage for A13 based machines
Signed-off-by: Sebastian Panceac <spanceac@gmail.com>

Fix boot of A13 based machines

---

recipes-kernel/linux/linux-mainline.inc
recipes-kernel/linux/linux-sunxi_3.4.bb

Traceback (most recent call last):
File "${TOPDIR}/../src/poky/scripts/devtool", line 338, in <module>
ret = main()
File "${TOPDIR}/../src/poky/scripts/devtool", line 325, in main
ret = args.func(args, config, basepath, workspace)
File "${TOPDIR}/../src/poky/scripts/lib/devtool/standard.py", line 834, in modify
if (os.path.exists(srcdir) and os.listdir(srcdir)) and (kernelVersion in staging_kerVer and staging_kbranch == kbranch):
TypeError: 'in <string>' requires string as left operand, not NoneType
Where 'kernelVersion' is None that cause an error.
In the code: "kernelVersion = rd.getVar('LINUX_VERSION')"
So LINUX_VERSION should be initialized
Signed-off-by: Ilja Byckevich <iljabyckevich@gmail.com>

linux-mainline: fix 'devtool modify' command fail

---

conf/layer.conf

Adhere to naming convention as stated in Yocto manual section 1.3.5 Layer Configuration File.

Adhere naming convention

---

conf/machine/orange-pi-zero.conf

Using the name of this machine variable resulted in an incorrect build. This commit updates the machine name to the correct format and it updates the description.

Fix incorrect machine variable

---

conf/machine/include/sunxi64.inc

The change for #375 does not work as it does not include the generated dt in the boot parition. This fixes it.

fix wic including the device tree file in IMAGE_BOOT_FILES

---

recipes-kernel/linux/linux-mainline-6.1.9/orange-pi-zero2/0011-dts-add-usb-to-h616.patch
recipes-kernel/linux/linux-mainline-6.1.9/orange-pi-zero2/0012-dts-orange-pi-zero2.patch
recipes-kernel/linux/linux-mainline_6.1.9.bb

back port from 6.2 with usb support for this board. tested.

Add usb support for orange pi zero 2

---

recipes-bsp/u-boot/files/0003-sunxi-H6-Enable-Ethernet-on-Orange-Pi-One-Plus.patch
recipes-bsp/u-boot/u-boot_%.bbappend

This patch adds ethernet support to orange pi one plus. The patch has been submitted to the mailing list and is being added to the bbappend for u-boot.
Unfortunately, is doesn't keep ethernet on after kernel boot, as the kernel dts needs to be synced with the u-boot dts.
Submitted patch waiting for approval on the upstream: https://lore.kernel.org/u-boot/30debca8b31ed4d2cbd64850d48b81ac@posteo.net/T/#t

add u-boot ethernet support to orange pi one plus (h6)

---

recipes-bsp/trusted-firmware-a/trusted-firmware-a_%.bbappend
recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
recipes-kernel/linux-firmware/linux-firmware_%.bbappend
recipes-kernel/linux/linux.inc

Start a bit of work towards [Yocto Compatibility](https://docs.yoctoproject.org/dev-manual/layers.html#making-sure-your-layer-is-compatible-with-yocto-project). In particular, avoid changing the behaviour of certain recipes based solely on the presence of the meta-sunxi layer.
With these changes the behaviour of several recipes no longer change unless we're using a sunxi machine.

Fix various Yocto compatibility issues

---

conf/machine/orange-pi-prime.conf
recipes-kernel/linux/linux-mainline.inc
recipes-kernel/linux/linux-mainline/orange-pi-prime/0001-dts-sun50i-h5-enable-power-button-for-orange-pi-prime.patch
recipes-kernel/linux/linux-mainline/orange-pi-prime/0002-dts-sun50i-h5-orange-pi-prime-add-regulator.patch
recipes-kernel/linux/linux-mainline/orange-pi-prime/0003-dts-sun50i-h5-orange-pi-prime-add-rtl8723cs.patch

- Ethernet, WiFi, Bluetooth, USBs are working fine but HDMI is working until U-Boot loading the kernel. Then it stop working.
- Tested with core-image-base and kernel mainline 6.6.28

Add Orange Pi Prime machine support

---

recipes-kernel/linux/linux.inc

Use SPDX name for the kernel, oe-core changed a long time ago and now we're throwing licence name warnings.
Cherry-picked f8aeeaeddb2357bfa15bc2b56ce6f44361b60bb1 from branch master as it relevant to branch scarthgap too.

linux: change licence name

---

recipes-bsp/u-boot/u-boot_%.bbappend

For all boards except mangopi-mq-t-tt13, switch back the serial console to ttyS0. Apply the ttyS3 patch added in commit [1] only when building for the mangopi-mq-t-tt13 board.
Boot tested on orangepi-zero2 board - the kernel logs are again printed to the debug serial console.
[1] 9edbede7bcc3 ("u-boot: Fix console for mangopi-mq-r-tt13 board")

u-boot: apply ttyS3 patch only for mangopi-mq-t-tt13 builds

---

conf/machine/cubieboard4.conf

Add machine `cubieboard4` for Cubieboard 4 with Allwinner A80 SoC from the sun9i family with mainline U-Boot and Linux kernel.
Thanks to @lazarh for testing core-image-base on the machine.

cubieboard4.conf: Add machine

---

recipes-devtools/python/pya20_0.2.12.bb

distutils3 is deprecated and its use produces warnings during build:
~~~
WARNING: distutils-common-base.bbclass is deprecated, please use setuptools3-base.bbclass instead
WARNING: distutils3-base.bbclass is deprecated, please use setuptools3-base.bbclass instead
WARNING: distutils3.bbclass is deprecated, please use setuptools3.bbclass instead
~~~
setuptools3 should be a drop-in replacement.

recipes/devtools: replace distutils3*.bbclass with setuptools3*.bbclass

---

recipes-kernel/linux/linux-mainline.inc
recipes-kernel/linux/linux-mainline/6.5/0005-ARM-dts-sunxi-Add-MMC-alias-for-consistent-enumerati.patch

As suggested in https://github.com/linux-sunxi/meta-sunxi/pull/431, add patch that adds MMC aliases to device tree for consistent enumeration of SD cards. Patch got denied upstream [1], so adding it here to linux-mainline. This should fix spurious boot failures experienced on Olinuxino A20 MICRO.
[1] https://lore.kernel.org/lkml/CAGb2v67dBhL3-AhLeHg3xOgbNZ3qu0aj9+kA+MoOMRYfr_Z_zQ@mail.gmail.com/

recipes-kernel/linux-mainline: add MMC alias for Olinuxino A20

---

conf/machine/bananapi-m2-berry.conf
recipes-kernel/linux-firmware/linux-firmware_%.bbappend
recipes-kernel/linux/linux-mainline.inc

Add `bananapi-m2-berry` machine conf and enable WiFi for it.
I didn't test much, but I was able to start `core-image-weston` after increasing CMA size via kernel cmdline and ping stuff via WiFi.
Let me know if you need more info or testing, thanks!

Add BananaPi M2 Berry support

---

recipes-kernel/linux/linux-mainline.inc
recipes-kernel/linux/linux-mainline/6.5/0006-dts-allwinner-orangepi-zero-mmc-aliases-for-consiste.patch

This fixes random boot failures.
Same workaround as in the other patches.

linux-mainline: dts: orangepi-zero: add mmc aliases for consistent enumeration

---

recipes-kernel/linux/linux-mainline_6.6.85.bb

Update to latest patch release for bug and CVE fixes

linux-mainline: bump to 6.6.85

---

conf/layer.conf
recipes-kernel/linux/linux.inc

- conf/layer.conf:Support Yocto release Walnascar.
- linux.inc: Switch from virtual/XXX-gcc to virtual/cross-cc (and c++/binutils) as in [Poky commit 90e0a0f7f4536e1aeb311ab2b061be71b4129e4e](https://web.git.yoctoproject.org/poky/commit/?id=90e0a0f7f4536e1aeb311ab2b061be71b4129e4e)

Support Walnascar

---

conf/machine/olinuxino-a20som204.conf
recipes-devtools/python/pya20_0.2.12.bb

Add support for Olimex A20-SOM204-EVB board. It is an expansion board
for the Olimex A20-SOM204 SOM that uses the sun7i Allwinner A20 Soc:
https://github.com/OLIMEX/SOM204
It is supported in U-Boot and mainline Linux kernel.

Add support for Olimex A20-SOM204-EVB board 
