linux-sunxi/meta-sunxi

conf/machine/cubieboard2.conf
=> Fix cubieboard2.conf.

recipes-graphics/libgles/sunxi-mali/0002-Add-missing-GLchar-definition.patch, recipes-graphics/libgles/sunxi-mali/0003-Fix-sed-to-replace-by-the-correct-var.patch, recipes-graphics/libgles/sunxi-mali_git.bb, recipes-graphics/xorg-xserver/xf86-video-fbturbo_git.bb
Part of these fixes were already included in dora branch. Fixes some EGL missing errors. Tested on current fido.
=> sunxi-mali fixes

recipes-graphics/xorg-xserver/xf86-video-fbturbo_git.bb
=> xf86-video-fbturbo: add DEPENDS

recipes-bsp/u-boot/u-boot-sunxi.bb, recipes-bsp/u-boot/u-boot-sunxi/0002-gcc5-fixes.patch, recipes-graphics/libgles/sunxi-mali/0001-fix-test-build.patch, recipes-graphics/libgles/sunxi-mali_git.bb, recipes-kernel/linux/linux-sunxi/0001-gcc5-fixes.patch, recipes-kernel/linux/linux-sunxi_3.4.bb
Update to the latest linux-sunxi kernel on the sunxi-3.4 branch.
=> linux-sunxi_3.4: bump kernel version

recipes-kernel/linux/linux_4.1.15.bb, recipes-kernel/linux/linux_git.bb
Bump stable kernel to 4.1.15
Bump git kernel to 4.4rc5
Signed-off-by: Jens Lucius info@jenslucius.com
=> Bump kernel versions

classes/sdcard_image-sunxi.bbclass
See https://github.com/linux-sunxi/meta-sunxi/issues/137
=> Fixed dtb deployment for krogoth

classes/sdcard_image-sunxi.bbclass
A couple of fixes required for building images with OE-Core master.
=> Image class fixes

recipes-bsp/u-boot/u-boot_2016.09.01.bb
=> u-boot: update to 2016.09.01

recipes-bsp/u-boot/u-boot_2016.11.bb
=> u-boot: update to 2016.11

recipes-support/sunxi-tools/sunxi-tools_git.bb
Sunxi-tools wasn't even building. This commit fixes that.
Please merge to morty and master.
=> fixes sunxi-tools build and updates to lastest version (1.4)

conf/machine/orange-pi-pc-plus.conf
Added base config to be able to build orangepi pc -plus
=> Added configuration for orangepi pc plus

recipes-kernel/linux/linux.inc
Signed-off-by: Koen Kooi <koen.kooi@linaro.org>
=> Fix parse failure with sumo and master

README.md
Update and improve the information in section
"Kernel / U-Boot Version".
Signed-off-by: Leon Anavi <leon@anavi.org>
=> README.md: Update Kernel / U-Boot Version

README.md, conf/layer.conf
Fixes https://github.com/linux-sunxi/meta-sunxi/issues/254
=> Layerdepends

conf/machine/pcduino3.conf
Adds machine configuration for Linksprite's pcDuino3 A20 board
=> Added pcDuino3 Board

recipes-kernel/linux/linux-mainline/orange-pi-zero/0001-dts-orange-pi-zero-Add-wifi-support.patch, recipes-kernel/linux/linux-mainline_4.19.63.bb, recipes-kernel/linux/linux-mainline_5.2.5.bb, recipes-kernel/linux/linux-mainline_5.3-rc2.bb
=> linux: refresh orange-pi-zero wifi patch

recipes-kernel/linux/linux-mainline_4.19.81.bb, recipes-kernel/linux/linux-mainline_5.3.8.bb, recipes-kernel/linux/linux-mainline_5.4-rc6.bb
Update kernel recipes to latest revisions available upstream.
=> Update kernel recipes to latest revisions

conf/layer.conf
Update the layer compatibility information to indicate this layer is
compatible with "dunfell".
=> layer.conf: add "dunfell" compatibility

recipes-bsp/u-boot/files/0001-nanopi_neo_air_defconfig-Enable-eMMC-support.patch
=> u-boot: rebase patch against v2020.04

recipes-kernel/linux/linux-mainline_5.4.18.bb, recipes-kernel/linux/linux-mainline_5.4.69.bb
=> linux-mainline: update to lt 5.4.69

conf/machine/nanopi-m1.conf
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> machine: nanopi-m1: add config

conf/machine/licheepi-zero.conf
Adding Lichee Pi Zero machine (booted)
=> adding Lichee Pi Zero machine (booted)

conf/machine/bananapi-m2m.conf
=> Added bananapi-m2m machine

conf/machine/bananapi-m2m.conf, recipes-kernel/linux/linux-mainline_4.19.186.bb, recipes-kernel/linux/linux-mainline_5.4.111.bb, recipes-kernel/linux/linux-mainline_5.4.69.bb
- bump kernels to latest versions
- add bananapi m2m machine
=> Misc fixes

conf/machine/bananapi-m64.conf
=> bananapi m64

conf/machine/orange-pi-plus2e.conf
Hi there, I have tested this and it works. So, I figured I would share. Please let me know if you'd like any modifications made.
=> Orange Pi Plus 2E Machine Configuration

recipes-bsp/u-boot/u-boot_%.bbappend
Same as #314, without this patch booting ends with Starting kernel ...
=> Fix nanopi-neo booting on Dunfell

conf/layer.conf
=> Fix inherit distutils3 error

conf/layer.conf
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
=> layer.conf: add langdale compatibility

conf/layer.conf
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
=> layer: add mickledore compatibility

recipes-kernel/linux/linux-mainline-6.1.9/orange-pi-zero2/0002-drv-wireless-driver-for-uwe5622-allwinner-bugfix.patch, recipes-kernel/linux/linux-mainline-6.1.9/orange-pi-zero2/0003-drv-fix-incldue-path-for-unisocwcn.patch
This pull request fixes build problems that occur during patching the kernel. Fixes #370 issue.
=> Fix file permissions in patches for Orange Pi Zero 2 with Kernel 6x

recipes-bsp/u-boot/files/0001-nanopi_neo_air_defconfig-Enable-eMMC-support.patch, recipes-bsp/u-boot/files/0002-Added-nanopi-r1-board-support.patch
=> Fixes Upstream-Status lines in a few u-boot patches

conf/machine/orange-pi-lite.conf
I tested it with mainline 6.1.9
=> New device Orange PI lite

conf/machine/include/sunxi.inc, conf/machine/include/sunxi64.inc, recipes-bsp/u-boot/files/arm/boot.cmd, recipes-kernel/linux/linux-mainline.inc, recipes-kernel/linux/linux-mainline/6.5/0001-dts-orangepi-zero-Add-wifi-support.patch, recipes-kernel/linux/linux-mainline/6.5/0002-dts-nanopi-neo-air-Add-camera-support.patch, recipes-kernel/linux/linux-mainline/6.5/0003-dts-allwinner-bananapi-m2-zero-Enforce-consistent-MM.patch, recipes-kernel/linux/linux-mainline/6.5/0004-dts-allwinner-bananapi-m64-Consistent-nodes-for-mmc-devices.patch, recipes-kernel/linux/linux-mainline_6.5.8.bb
- update kernel to 6.5
- fixes regarding prefix for arm32 dts
=> Kernel 6.5 updates

recipes-bsp/u-boot/files/0005-Added-dtb-for-sun8i-h3-nanopi-r1-device.patch, recipes-bsp/u-boot/files/0006-nanopi-r1-dts-fixes.patch, recipes-bsp/u-boot/u-boot_%.bbappend
Added missing dts + small dts fix.
=> u-boot:Added fixes for nanopi-r1 board

recipes-kernel/linux/linux-mainline/6.5/0001-dts-orangepi-zero-Add-wifi-support.patch, recipes-kernel/linux/linux-mainline/6.5/0002-dts-nanopi-neo-air-Add-camera-support.patch, recipes-kernel/linux/linux-mainline/6.5/0003-dts-allwinner-bananapi-m2-zero-Enforce-consistent-MM.patch, recipes-kernel/linux/linux-mainline/6.5/0004-dts-allwinner-bananapi-m64-Consistent-nodes-for-mmc-devices.patch
Add Upstream-Status in patches to fix QA issues.
=> linux-mainline/6.5/*.patch: Add Upstream-Status
